Implement take_while
Crazytieguy/gat-lending-iterator pull request #21
Opened 2023-12-05 18:55 UTC by equas

2023-12-05 19:23 UTC, ratmice requested changes

2023-12-05 19:23 UTC, ratmice commented on src/adapters/take_while.rs
> +#[derive(Clone, Copy)]
`std::iter::TakeWhile` doesn't have the `Copy` derive, I don't see why it would be needed?
`Iterator + Copy` is generally seen as a footgun[^1] I don't see why that wouldn't also be the case for `LendingIterator`.

[^1]: https://github.com/rust-lang/rust-clippy/issues/1534

2023-12-05 22:11 UTC, equas commented on src/adapters/take_while.rs
> +#[derive(Clone, Copy)]
You're right of course

2023-12-06 06:42 UTC, ratmice approved these changes

2023-12-06 06:46 UTC, ratmice commented
With that changed it looked good to me, it would be nice to have a test though

2023-12-06 08:53 UTC, Crazytieguy commented
Looks good to me 🙂. I'm planning at some point to add tests to everything with uniform style and such, so I'm not too worried about tests right now. If you want to add tests you're welcome but it's not a blocker for merging as far as I'm concerned

2023-12-09 03:51 UTC, merged